// web/src/views/Player.vue
<template>
  <div>
    <h2>实时观看</h2>
    <div class="stage">
      <video ref="video" autoplay playsinline muted></video>
      <div class="status">{{ status }}</div>
    </div>
    <div class="info">
      <span>房间: {{ room }}</span>
      <button @click="connect">连接</button>
      <button @click="disconnect">断开</button>
    </div>
  </div>
</template>

<script>
import { ref, onMounted, onUnmounted } from 'vue'
import api from '../api/client'
import { Room, RoomEvent } from 'livekit-client'

export default {
  props: { room: { type: String, required: true } },
  setup(props) {
    const video = ref(null)
    const status = ref('未连接')
    let lkRoom = null
    let mediaStream = null

    function resetStream() {
      if (video.value) video.value.srcObject = null
      if (mediaStream) {
        mediaStream.getTracks().forEach((t) => t.stop())
        mediaStream = null
      }
    }

    async function connect() {
      status.value = '获取 token...'
      const identity = 'viewer-' + Date.now()
      const r = await api.get('/api/token', {
        params: { room: props.room, identity, role: 'viewer' }
      })
      const { token, url } = r.data

      resetStream()
      mediaStream = new MediaStream()
      if (video.value) video.value.srcObject = mediaStream

      lkRoom = new Room()
      lkRoom.on(RoomEvent.TrackSubscribed, (track) => {
        if (track.kind === 'video') {
          mediaStream.addTrack(track.mediaStreamTrack)
          status.value = '播放中 (WebRTC)'
        }
      })
      lkRoom.on(RoomEvent.TrackUnsubscribed, (track) => {
        mediaStream.removeTrack(track.mediaStreamTrack)
      })
      lkRoom.on(RoomEvent.Disconnected, () => { status.value = '已断开' })

      try {
        await lkRoom.connect(url, token)
        status.value = '已连接房间: ' + props.room
      } catch (e) {
        status.value = '连接失败: ' + (e.message || e)
      }
    }

    async function disconnect() {
      if (lkRoom) {
        await lkRoom.disconnect()
        lkRoom = null
      }
      resetStream()
      status.value = '未连接'
    }

    onMounted(() => { if (props.room) connect() })
    onUnmounted(() => { if (lkRoom) lkRoom.disconnect() })

    return { video, status, connect, disconnect }
  }
}
</script>

<style scoped>
.stage { background: #000; border-radius: 8px; min-height: 360px; display: flex; align-items: center; justify-content: center; overflow: hidden; position: relative; margin: 16px 0; }
video { width: 100%; max-height: 70vh; }
.status { position: absolute; top: 10px; left: 10px; background: rgba(0,0,0,.7); padding: 4px 10px; border-radius: 4px; font-size: 12px; color: #22c55e; }
.info { display: flex; gap: 12px; align-items: center; }
button { padding: 8px 14px; background: #2563eb; color: #fff; border: none; border-radius: 6px; cursor: pointer; }
</style>

// web/src/pages/Player.jsx
import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { LiveKitRoom, RoomAudioRenderer, useTracks, VideoTrack } from '@livekit/components-react'
import { Track } from 'livekit-client'
import api from '../api'

function CameraTracks() {
  const tracks = useTracks([{ source: Track.Source.Camera, withPlaceholder: false }])
  if (!tracks.length) return <div className="status-tip">等待视频轨道...</div>
  return (
    <div className="stage">
      {tracks.map((t) => (
        <VideoTrack key={t.participant.identity} trackRef={t} />
      ))}
    </div>
  )
}

export default function Player() {
  const { room } = useParams()
  const [conn, setConn] = useState(null)

  useEffect(() => {
    let alive = true
    setConn(null)
    const identity = 'viewer-' + Date.now()
    api
      .get('/api/token', { params: { room, identity, role: 'viewer' } })
      .then((r) => { if (alive) setConn({ token: r.data.token, url: r.data.url }) })
      .catch((e) => { if (alive) setConn({ error: e.response?.data?.error || e.message }) })
    return () => { alive = false }
  }, [room])

  if (conn?.error) return <div className="error">连接失败: {conn.error}</div>
  if (!conn) return <div>获取 token...</div>

  return (
    <div>
      <h2>实时观看</h2>
      <LiveKitRoom
        serverUrl={conn.url}
        token={conn.token}
        connect={true}
        audio={false}
        video={true}
        style={{ height: '70vh' }}
      >
        <RoomAudioRenderer />
        <CameraTracks />
      </LiveKitRoom>
      <p className="hint">房间: {room}</p>
      <style>{`
        .stage { display: grid; grid-template-columns: 1fr; gap: 8px; background: #000; border-radius: 8px; overflow: hidden; height: 100%; }
        .stage video { width: 100%; height: 100%; object-fit: contain; }
        .status-tip { display: flex; align-items: center; justify-content: center; height: 100%; color: #6b7280; }
      `}</style>
    </div>
  )
}
